# Generated by Django 6.0 on 2025-12-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleancharcoal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='000000000', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sector',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
