# Generated by Django 6.0 on 2025-12-14 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleancharcoal_app', '0002_alter_profile_district_alter_profile_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('burner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burner_appointments', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='cleancharcoal_app.appointment')),
                ('burner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kiln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('work_province', models.CharField(default='Unknown', max_length=100)),
                ('work_district', models.CharField(default='Unknown', max_length=100)),
                ('work_sector', models.CharField(default='Unknown', max_length=100)),
                ('work_cell', models.CharField(blank=True, max_length=100, null=True)),
                ('work_village', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kilns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiln_district', models.CharField(max_length=100)),
                ('kiln_sector', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='docs/id/')),
                ('land_certificate', models.FileField(blank=True, null=True, upload_to='docs/land/')),
                ('coop_certificate', models.FileField(blank=True, null=True, upload_to='docs/coop/')),
                ('tree_age_proof', models.FileField(blank=True, null=True, upload_to='docs/tree_age/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('appointment_required', 'Appointment Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('burner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL)),
                ('kiln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='cleancharcoal_app.kiln')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='cleancharcoal_app.permissionrequest'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('smoke', 'Smoke'), ('co2', 'CO2'), ('pm25', 'PM2.5'), ('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=30)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('kiln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='cleancharcoal_app.kiln')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='cleancharcoal_app.sensor')),
            ],
        ),
    ]
